ARG golang_src_repo=golang:latest
ARG photon_src_repo=photon:latest

FROM ${golang_src_repo} as build
ENV BUILD_PATH "github.com/vmware/global-load-balancing-services-for-kubernetes/"
RUN mkdir -p $GOPATH/src/$BUILD_PATH

COPY . $GOPATH/src/$BUILD_PATH
WORKDIR $GOPATH/src/$BUILD_PATH

RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux go build -o $GOPATH/bin/amko-service-discovery -mod=vendor $BUILD_PATH/cmd/service_discovery

FROM ${photon_src_repo}
RUN yum install -y tar.x86_64
COPY --from=build /go/bin/amko-service-discovery .
ENTRYPOINT [ "./amko-service-discovery" ]
