apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiclusteringresses.amko.vmware.com
spec:
  conversion:
    strategy: None
  group: amko.vmware.com
  names:
    kind: MultiClusterIngress
    listKind: MultiClusterIngressList
    plural: multiclusteringresses
    shortNames:
    - mci
    singular: multiclusteringress
  scope: Namespaced

  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              hostName:
                description: "FQDN of the ingresses of tenant clusters, from which MCI is built"
                type: "string"
              secretName:
                description: "Name of the secret object associated with the hostName in the MCI object"
                type: string
              config:
                description: "Configuration of the tenant target services"
                type: array
                items:
                  type: object
                  properties:
                    path:
                      description: "path specified in the tenant cluster's ingress object"
                      type: "string"
                    cluster:
                      description: "cluster context name of the tenant cluster"
                      type: "string"
                    service:
                      description: "kubernetes backend service and port configuration in the tenant cluster"
                      type: object
                      properties:
                        namespace:
                          description: "namespace of the target service in the kubernetes cluster"
                          type: "string"
                        name:
                          description:  "target service name in the tenant cluster"
                          type: "string"
                        port:
                          description: "port number of the target service in the tenant cluster"
                          type: "integer"
                          minimum: 1
                          maximum: 65535
                    weight:
                      description: "weight of this member in the resultant virtual service"
                      type: "integer"
                      minimum: 1
                      maximum: 100
          status:
            type: object
            properties:
              loadBalancer:
                description: "represents the load balancing properties of this object"
                type: object
                properties:
                  ingress:
                    description: "represents the ingress details like vip assigned to this object"
                    type: array
                    items:
                      type: object
                      properties:
                        hostname:
                          description:  "host fqdn handled by this multi cluster ingress resource"
                          type: "string"
                        ip:
                          description: "virtual IP address assigned to this object by the load balancer"
                          type: string
              backends:
                description: "status of backend resolution for this MCI's configuration"
                type: "array"
                items:
                  type: object
                  properties:
                    cluster:
                      description: "tenant cluster's cluster context"
                      type: "string"
                    namespace:
                      description: "namespace of the target backend in the tenant cluster"
                      type: "string"
                    service:
                      description: "name of the target backend service in the tenant cluster"
                      type: "string"
                    endpoints:
                      description: "list of endpoints of the target backends in the tenant cluster"
                      type: array
                      items:
                        type: object
                        properties:
                          ip:
                            description: "IP address of the endpoint fetched from the tenant cluster"
                            type: "string"
                          port:
                            type: integer

        required:
        - spec
    served: true
    storage: true
