/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware/global-load-balancing-services-for-kubernetes/internal/apis/amko/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMCIs implements MCIInterface
type FakeMCIs struct {
	Fake *FakeAmkoV1alpha1
	ns   string
}

var mcisResource = schema.GroupVersionResource{Group: "amko.vmware.com", Version: "v1alpha1", Resource: "mcis"}

var mcisKind = schema.GroupVersionKind{Group: "amko.vmware.com", Version: "v1alpha1", Kind: "MCI"}

// Get takes name of the mCI, and returns the corresponding mCI object, and an error if there is any.
func (c *FakeMCIs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MCI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mcisResource, c.ns, name), &v1alpha1.MCI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MCI), err
}

// List takes label and field selectors, and returns the list of MCIs that match those selectors.
func (c *FakeMCIs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MCIList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mcisResource, mcisKind, c.ns, opts), &v1alpha1.MCIList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MCIList{ListMeta: obj.(*v1alpha1.MCIList).ListMeta}
	for _, item := range obj.(*v1alpha1.MCIList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mCIs.
func (c *FakeMCIs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mcisResource, c.ns, opts))

}

// Create takes the representation of a mCI and creates it.  Returns the server's representation of the mCI, and an error, if there is any.
func (c *FakeMCIs) Create(ctx context.Context, mCI *v1alpha1.MCI, opts v1.CreateOptions) (result *v1alpha1.MCI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mcisResource, c.ns, mCI), &v1alpha1.MCI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MCI), err
}

// Update takes the representation of a mCI and updates it. Returns the server's representation of the mCI, and an error, if there is any.
func (c *FakeMCIs) Update(ctx context.Context, mCI *v1alpha1.MCI, opts v1.UpdateOptions) (result *v1alpha1.MCI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mcisResource, c.ns, mCI), &v1alpha1.MCI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MCI), err
}

// Delete takes name of the mCI and deletes it. Returns an error if one occurs.
func (c *FakeMCIs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mcisResource, c.ns, name), &v1alpha1.MCI{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMCIs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mcisResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MCIList{})
	return err
}

// Patch applies the patch and returns the patched mCI.
func (c *FakeMCIs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MCI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mcisResource, c.ns, name, pt, data, subresources...), &v1alpha1.MCI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MCI), err
}
