apiVersion: v1
kind: Secret
metadata:
  name: "gslb-avi-secret"
  namespace: {{ .Release.Namespace }}
  {{- with .Values.secret.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ .Values.gslbLeaderCredentials.username | b64enc }}
  password: {{ .Values.gslbLeaderCredentials.password | b64enc }}
